part of '../../../app/app.dart';

final _networkGraphContractPreview = _NetworkGraphPayload.fromMap({
  'data': {
    'period': {
      'preset': '1y',
      'from': '2025-01-01',
      'to': '2025-12-31',
    },
    'lanes': ['root_company', 'client_company', 'contract', 'employee'],
    'nodes': [
      {
        'publicId': 'egr_01hroot0000000000000001',
        'nodeType': 'root_company',
        'lane': 'root_company',
        'displayName': 'Summit Holdings',
        'subtitle': 'Holding company',
        'status': 'active',
        'badges': ['1 client company', '1 active contract'],
        'detailSnapshot': {
          'kind': 'root_company',
          'summary': 'Raiz principal da carteira Summit no preview contratual.',
          'activeClientCompanies': 1,
          'activeContracts': 1,
          'activeEmployees': 1,
          'cta': {
            'label': 'Ver grupo completo',
            'targetPublicId': 'egr_01hroot0000000000000001',
          },
        },
      },
      {
        'publicId': 'egr_01hroot0000000000000002',
        'nodeType': 'root_company',
        'lane': 'root_company',
        'displayName': 'Pioneer Group',
        'subtitle': 'Holding company',
        'status': 'active',
        'badges': ['1 client company', '2 relevant contracts'],
        'detailSnapshot': {
          'kind': 'root_company',
          'summary': 'Raiz Pioneer com contrato ativo e historico relevante.',
          'activeClientCompanies': 1,
          'activeContracts': 2,
          'activeEmployees': 1,
          'historicalEmployees': 1,
          'cta': {
            'label': 'Ver grupo completo',
            'targetPublicId': 'egr_01hroot0000000000000002',
          },
        },
      },
      {
        'publicId': 'cli_01hcli0000000000000002',
        'nodeType': 'client_company',
        'lane': 'client_company',
        'displayName': 'Summit Solutions Inc.',
        'subtitle': 'Client company',
        'status': 'active',
        'badges': ['1 active contract', '1 indirect bridge'],
        'detailSnapshot': {
          'kind': 'client_company',
          'summary': 'Cliente Summit com ponte indireta para Pioneer Services.',
          'rootCompanies': ['Summit Holdings'],
          'activeContracts': 1,
          'indirectConnections': 1,
          'cta': {
            'label': 'Abrir empresa cliente',
            'targetPublicId': 'cli_01hcli0000000000000002',
          },
        },
      },
      {
        'publicId': 'cli_01hcli0000000000000003',
        'nodeType': 'client_company',
        'lane': 'client_company',
        'displayName': 'Pioneer Services LLC',
        'subtitle': 'Client company',
        'status': 'active',
        'badges': ['2 relevant contracts'],
        'detailSnapshot': {
          'kind': 'client_company',
          'summary':
              'Cliente Pioneer com contrato ativo e historico visivel no mesmo recorte.',
          'rootCompanies': ['Pioneer Group'],
          'activeContracts': 2,
          'activeEmployees': 2,
          'cta': {
            'label': 'Abrir empresa cliente',
            'targetPublicId': 'cli_01hcli0000000000000003',
          },
        },
      },
      {
        'publicId': 'ctr_01hctr0000000000000002',
        'nodeType': 'contract',
        'lane': 'contract',
        'displayName': 'IT Services Contract',
        'subtitle': 'Active',
        'status': 'active',
        'badges': ['1 employee'],
        'detailSnapshot': {
          'kind': 'contract',
          'summary': 'Contrato ativo de TI ligado a Summit Solutions.',
          'contractStatus': 'active',
          'clientCompanies': ['Summit Solutions Inc.'],
          'activeEmployees': 1,
          'cta': {
            'label': 'Abrir contrato',
            'targetPublicId': 'ctr_01hctr0000000000000002',
          },
        },
      },
      {
        'publicId': 'ctr_01hctr0000000000000004',
        'nodeType': 'contract',
        'lane': 'contract',
        'displayName': 'Maintenance Contract',
        'subtitle': 'Active',
        'status': 'active',
        'badges': ['2 companies in context', '2 employees'],
        'detailSnapshot': {
          'kind': 'contract',
          'summary':
              'Contrato que prova que o mesmo no pode carregar mais de uma company relevante no recorte.',
          'contractStatus': 'active',
          'clientCompanies': ['Pioneer Services LLC', 'Pioneer Retail Inc.'],
          'activeEmployees': 1,
          'historicalEmployees': 1,
          'cta': {
            'label': 'Abrir contrato',
            'targetPublicId': 'ctr_01hctr0000000000000004',
          },
        },
      },
      {
        'publicId': 'pes_01hpes0000000000000003',
        'nodeType': 'employee',
        'lane': 'employee',
        'displayName': 'Sarah Johnson',
        'subtitle': 'Employee with active and historical links',
        'status': 'historical',
        'badges': ['2 relevant contracts'],
        'detailSnapshot': {
          'kind': 'employee',
          'summary':
              'Pessoa que aparece com aresta ativa e historica no mesmo recorte.',
          'activeContracts': 1,
          'historicalContracts': 1,
          'cta': {
            'label': 'Abrir pessoa',
            'targetPublicId': 'pes_01hpes0000000000000003',
          },
        },
      },
      {
        'publicId': 'pes_01hpes0000000000000004',
        'nodeType': 'employee',
        'lane': 'employee',
        'displayName': 'Michael Chen',
        'subtitle': 'Employee with active maintenance link',
        'status': 'active',
        'badges': ['1 active contract'],
        'detailSnapshot': {
          'kind': 'employee',
          'summary': 'Pessoa ligada de forma ativa ao maintenance contract.',
          'activeContracts': 1,
          'cta': {
            'label': 'Abrir pessoa',
            'targetPublicId': 'pes_01hpes0000000000000004',
          },
        },
      },
    ],
    'edges': [
      {
        'publicId': 'rel_01hrelpreview000000000001',
        'fromPublicId': 'egr_01hroot0000000000000001',
        'toPublicId': 'cli_01hcli0000000000000002',
        'relationshipKind': 'client_membership',
        'relationshipState': 'active',
        'periodStart': '2024-01-01',
        'periodEnd': null,
        'metadata': {},
      },
      {
        'publicId': 'rel_01hrelpreview000000000002',
        'fromPublicId': 'egr_01hroot0000000000000002',
        'toPublicId': 'cli_01hcli0000000000000003',
        'relationshipKind': 'client_membership',
        'relationshipState': 'active',
        'periodStart': '2024-01-01',
        'periodEnd': null,
        'metadata': {},
      },
      {
        'publicId': 'rel_01hrelpreview000000000003',
        'fromPublicId': 'cli_01hcli0000000000000002',
        'toPublicId': 'cli_01hcli0000000000000003',
        'relationshipKind': 'indirect_association',
        'relationshipState': 'indirect',
        'periodStart': '2025-01-01',
        'periodEnd': null,
        'metadata': {'label': 'shared delivery context'},
      },
      {
        'publicId': 'rel_01hrelpreview000000000004',
        'fromPublicId': 'cli_01hcli0000000000000002',
        'toPublicId': 'ctr_01hctr0000000000000002',
        'relationshipKind': 'contract_allocation',
        'relationshipState': 'active',
        'periodStart': '2024-02-01',
        'periodEnd': null,
        'metadata': {},
      },
      {
        'publicId': 'rel_01hrelpreview000000000005',
        'fromPublicId': 'cli_01hcli0000000000000003',
        'toPublicId': 'ctr_01hctr0000000000000004',
        'relationshipKind': 'contract_allocation',
        'relationshipState': 'active',
        'periodStart': '2024-03-01',
        'periodEnd': null,
        'metadata': {},
      },
      {
        'publicId': 'rel_01hrelpreview000000000006',
        'fromPublicId': 'pes_01hpes0000000000000003',
        'toPublicId': 'ctr_01hctr0000000000000002',
        'relationshipKind': 'employment_link',
        'relationshipState': 'active',
        'periodStart': '2025-02-01',
        'periodEnd': null,
        'metadata': {'label': 'current allocation'},
      },
      {
        'publicId': 'rel_01hrelpreview000000000007',
        'fromPublicId': 'pes_01hpes0000000000000003',
        'toPublicId': 'ctr_01hctr0000000000000004',
        'relationshipKind': 'employment_link',
        'relationshipState': 'historical',
        'periodStart': '2024-01-01',
        'periodEnd': '2024-12-31',
        'metadata': {'label': 'previous allocation'},
      },
      {
        'publicId': 'rel_01hrelpreview000000000008',
        'fromPublicId': 'pes_01hpes0000000000000004',
        'toPublicId': 'ctr_01hctr0000000000000004',
        'relationshipKind': 'employment_link',
        'relationshipState': 'active',
        'periodStart': '2025-03-01',
        'periodEnd': null,
        'metadata': {'label': 'maintenance squad'},
      },
    ],
    'filters': {
      'search': '',
      'applied': {
        'periodPreset': '1y',
        'rootCompanyPublicIds': [],
        'clientCompanyPublicIds': [],
        'contractStatuses': ['active', 'expired'],
        'employeeStatuses': ['active', 'historical'],
        'includeHistorical': true,
        'includeIndirect': true,
      },
      'available': {
        'periodPresets': ['6m', '1y', '2y', 'all'],
        'rootCompanies': [
          {
            'publicId': 'egr_01hroot0000000000000001',
            'label': 'Summit Holdings',
          },
          {
            'publicId': 'egr_01hroot0000000000000002',
            'label': 'Pioneer Group',
          },
        ],
        'clientCompanies': [
          {
            'publicId': 'cli_01hcli0000000000000002',
            'label': 'Summit Solutions Inc.',
          },
          {
            'publicId': 'cli_01hcli0000000000000003',
            'label': 'Pioneer Services LLC',
          },
        ],
        'contractStatuses': ['active', 'expired'],
        'employeeStatuses': ['active', 'historical'],
        'relationshipStates': ['active', 'historical', 'indirect'],
      },
    },
    'legend': {
      'relationshipStates': [
        {'value': 'active', 'label': 'Active Relationship'},
        {'value': 'historical', 'label': 'Historical Relationship'},
        {'value': 'indirect', 'label': 'Indirect Relationship'},
      ],
    },
    'focus': {
      'selectedNodePublicId': 'pes_01hpes0000000000000003',
      'hoveredNodePublicId': null,
      'viewportAnchorPublicId': 'pes_01hpes0000000000000003',
    },
  },
  'meta': {
    'traceId': 'req_01hnetworkcontractpreview0001',
  },
});
