part of '../../../app/app.dart';

const _graphNodes = [
  _GraphNode(
    id: 'company_jotabe',
    kind: _GraphNodeKind.company,
    rootCompanyId: 'company_jotabe',
    label: 'SEDE JOTABE',
    subtitle:
        'Empresa-raiz com carteira propria e quadro terceirizado rastreavel.',
    miniLabel: 'empresa-raiz',
    position: Alignment(-0.88, -0.72),
    status: 'ativo',
    color: _tealColor,
    icon: Icons.apartment_outlined,
    highlights: [
      'Tem o mesmo peso estrutural da VVG dentro da teia.',
      'Ao ocultar esta raiz, clientes, contratos e colaboradores vinculados somem juntos.',
      'Funciona como ancora de rastreabilidade para origem do colaborador.',
    ],
    isRoot: true,
  ),
  _GraphNode(
    id: 'client_bela_vista',
    kind: _GraphNodeKind.company,
    rootCompanyId: 'company_jotabe',
    label: 'Condominio Bela Vista',
    subtitle: 'Cliente da carteira JOTABE com operacao de seguranca.',
    miniLabel: 'cliente',
    position: Alignment(-0.46, -0.58),
    status: 'ativo',
    color: _slateColor,
    icon: Icons.business_outlined,
    highlights: [
      'Empresa-cliente conectada a uma raiz especifica.',
      'Ajuda a deixar explicito para onde o colaborador foi subdirecionado.',
      'Pode ser ocultada de forma indireta ao desligar a visibilidade da raiz.',
    ],
  ),
  _GraphNode(
    id: 'contract_portaria',
    kind: _GraphNodeKind.contract,
    rootCompanyId: 'company_jotabe',
    label: 'CTR-SEG-2026-001',
    subtitle: 'Controle de acesso e ronda leve no Bela Vista.',
    miniLabel: 'contrato',
    position: Alignment(-0.04, -0.44),
    status: 'ativo',
    color: _amberColor,
    icon: Icons.description_outlined,
    highlights: [
      'Amarra o cliente ao quadro de seguranca alocado pela JOTABE.',
      'Permite filtrar a malha por setor e cargo sem perder a trilha da origem.',
      'Serve como ponte entre empresa-cliente e colaborador terceirizado.',
    ],
  ),
  _GraphNode(
    id: 'person_ana',
    kind: _GraphNodeKind.person,
    rootCompanyId: 'company_jotabe',
    label: 'Ana Paula Rocha',
    subtitle: 'Origem JOTABE | alocada no Bela Vista.',
    miniLabel: 'acesso',
    position: Alignment(0.42, -0.48),
    status: 'ativo',
    color: _tealColor,
    icon: Icons.badge_outlined,
    highlights: [
      'Mostra o caso classico de colaboradora vinculada a uma raiz e enviada para cliente especifico.',
      'Permite filtrar por setor, sexo, raca e tempo de servico sem perder a origem.',
      'Pode abrir ficha consolidada com trilha completa da alocacao.',
    ],
    sector: 'Seguranca',
    jobTitle: 'Controlador de Acesso',
    gender: 'feminino',
    race: 'branca',
    tenureMonths: 26,
  ),
  _GraphNode(
    id: 'client_horizonte',
    kind: _GraphNodeKind.company,
    rootCompanyId: 'company_jotabe',
    label: 'Horizonte Offices',
    subtitle: 'Cliente da carteira JOTABE com frente ADM e formacao.',
    miniLabel: 'cliente',
    position: Alignment(-0.46, -0.10),
    status: 'ativo',
    color: _slateColor,
    icon: Icons.business_outlined,
    highlights: [
      'Expande a teia para uma segunda carteira cliente da mesma raiz.',
      'Ajuda a provar que a ocultacao por raiz precisa derrubar toda a subarvore.',
      'Mantem contratos de apoio administrativo e entrada de aprendizes.',
    ],
  ),
  _GraphNode(
    id: 'contract_adm',
    kind: _GraphNodeKind.contract,
    rootCompanyId: 'company_jotabe',
    label: 'CTR-ADM-2026-014',
    subtitle: 'Apoio administrativo e formacao em escritorio.',
    miniLabel: 'contrato',
    position: Alignment(-0.02, -0.04),
    status: 'ativo',
    color: _amberColor,
    icon: Icons.description_outlined,
    highlights: [
      'Mantem cargos administrativos e de entrada no mesmo contexto contratual.',
      'Ajuda a demonstrar filtros dinamicos para setor e emprego especifico.',
      'Pode continuar visivel mesmo quando a leitura sai da seguranca.',
    ],
  ),
  _GraphNode(
    id: 'person_lucas',
    kind: _GraphNodeKind.person,
    rootCompanyId: 'company_jotabe',
    label: 'Lucas Andrade',
    subtitle: 'Origem JOTABE | frente administrativa ativa.',
    miniLabel: 'adm',
    position: Alignment(0.42, -0.08),
    status: 'ativo',
    color: _tealColor,
    icon: Icons.badge_outlined,
    highlights: [
      'Representa colaborador com advertencia anexa e tempo de casa mais longo.',
      'Ajuda a validar filtros de sexo, raca autodeclarada e advertencia.',
      'Mostra que o contrato pode sustentar mais de um perfil ocupacional.',
    ],
    sector: 'Area ADM',
    jobTitle: 'Supervisor Administrativo',
    gender: 'masculino',
    race: 'pardo',
    tenureMonths: 49,
    hasWarnings: true,
  ),
  _GraphNode(
    id: 'person_mila',
    kind: _GraphNodeKind.person,
    rootCompanyId: 'company_jotabe',
    label: 'Mila Santos',
    subtitle: 'Origem JOTABE | trilha de aprendizagem em andamento.',
    miniLabel: 'aprendiz',
    position: Alignment(0.68, 0.16),
    status: 'ativo',
    color: _tealColor,
    icon: Icons.school_outlined,
    highlights: [
      'Insere o eixo de estagiarios e jovens aprendizes na propria teia.',
      'Permite validar tempo de servico curto e recortes mais recentes de entrada.',
      'Mostra como a teia pode servir a contextos de formacao sem filtro fixo previo.',
    ],
    sector: 'Estagiarios + Jovens Aprendizes',
    jobTitle: 'Estagiaria Administrativa',
    gender: 'feminino',
    race: 'preta',
    tenureMonths: 7,
  ),
  _GraphNode(
    id: 'company_vvg',
    kind: _GraphNodeKind.company,
    rootCompanyId: 'company_vvg',
    label: 'VVG Servicos',
    subtitle: 'Empresa-raiz com carteira propria e equipe rastreavel.',
    miniLabel: 'empresa-raiz',
    position: Alignment(-0.88, 0.42),
    status: 'ativo',
    color: _roseColor,
    icon: Icons.apartment_outlined,
    highlights: [
      'Tem o mesmo peso estrutural da SEDE JOTABE.',
      'Pode ser desligada da teia inteira sem afetar a outra raiz.',
      'Explicita a necessidade de grupos empresariais independentes no mesmo mapa.',
    ],
    isRoot: true,
  ),
  _GraphNode(
    id: 'client_aurora',
    kind: _GraphNodeKind.company,
    rootCompanyId: 'company_vvg',
    label: 'Hospital Aurora',
    subtitle: 'Cliente da carteira VVG com frente de governanca.',
    miniLabel: 'cliente',
    position: Alignment(-0.46, 0.32),
    status: 'ativo',
    color: _slateColor,
    icon: Icons.local_hospital_outlined,
    highlights: [
      'Cliente conectado a uma segunda raiz de mesmo peso.',
      'Ajuda a demonstrar como contratos e desligados antigos podem reaparecer.',
      'Mantem a leitura de governanca, limpeza e historico na mesma subarvore.',
    ],
  ),
  _GraphNode(
    id: 'contract_governanca',
    kind: _GraphNodeKind.contract,
    rootCompanyId: 'company_vvg',
    label: 'CTR-GOV-2026-021',
    subtitle: 'Governanca operacional e lideranca de limpeza hospitalar.',
    miniLabel: 'contrato',
    position: Alignment(-0.02, 0.36),
    status: 'ativo',
    color: _amberColor,
    icon: Icons.description_outlined,
    highlights: [
      'Contrato que concentra ativos e desligados de varias janelas temporais.',
      'E um bom exemplo para habilitar 6 meses, 1 ano, 2 anos, 5 anos e todo o periodo.',
      'Tambem sustenta historico multiempresa em casos de passagem anterior.',
    ],
  ),
  _GraphNode(
    id: 'person_carla',
    kind: _GraphNodeKind.person,
    rootCompanyId: 'company_vvg',
    label: 'Carla Mendes',
    subtitle: 'Origem VVG | lideranca ativa em governanca.',
    miniLabel: 'governanca',
    position: Alignment(0.42, 0.24),
    status: 'ativo',
    color: _tealColor,
    icon: Icons.badge_outlined,
    highlights: [
      'Mantem o setor de governanca vivo na teia atual.',
      'Permite enxergar passagem anterior entre grupos empresariais.',
      'E um caso bom para abrir detalhe de risco, historico e relacoes cruzadas.',
    ],
    sector: 'Area de Governanca',
    jobTitle: 'Lider de Limpeza',
    gender: 'feminino',
    race: 'parda',
    tenureMonths: 18,
  ),
  _GraphNode(
    id: 'person_bruno',
    kind: _GraphNodeKind.person,
    rootCompanyId: 'company_vvg',
    label: 'Bruno Tavares',
    subtitle: 'Desligado ha 18 dias | historico ainda quente.',
    miniLabel: 'desligado',
    position: Alignment(0.58, 0.56),
    status: 'desligado',
    color: _roseColor,
    icon: Icons.person_off_outlined,
    highlights: [
      'Permanece visivel nas janelas curtas e some quando o recorte fecha abaixo de 18 dias.',
      'Ajuda a validar filtros de advertencia anexa e recortes juridicos.',
      'Continua rastreavel ate a raiz VVG e ao contrato hospitalar.',
    ],
    sector: 'Area de Governanca',
    jobTitle: 'Auxiliar de Limpeza',
    gender: 'masculino',
    race: 'preto',
    tenureMonths: 38,
    hasWarnings: true,
    dismissedDaysAgo: 18,
  ),
  _GraphNode(
    id: 'person_vera',
    kind: _GraphNodeKind.person,
    rootCompanyId: 'company_vvg',
    label: 'Vera Sousa',
    subtitle: 'Desligada ha 420 dias | historico remoto relevante.',
    miniLabel: 'historico',
    position: Alignment(0.26, 0.78),
    status: 'desligado',
    color: _roseColor,
    icon: Icons.person_off_outlined,
    highlights: [
      'Volta para a malha quando o usuario sobe para 2 anos ou todo o periodo.',
      'Prova que a teia nao pode limitar desligados antigos a um teto fixo de 90 dias.',
      'Mantem rastreabilidade de origem mesmo em desligamentos remotos.',
    ],
    sector: 'Area de Governanca',
    jobTitle: 'Governanta',
    gender: 'feminino',
    race: 'branca',
    tenureMonths: 86,
    dismissedDaysAgo: 420,
  ),
];

const _graphEdges = [
  _GraphEdge(
    from: 'company_jotabe',
    to: 'client_bela_vista',
    type: _GraphEdgeType.portfolio,
    detail: 'A SEDE JOTABE sustenta esta carteira cliente.',
  ),
  _GraphEdge(
    from: 'client_bela_vista',
    to: 'contract_portaria',
    type: _GraphEdgeType.scope,
    detail: 'Este cliente recebe o contrato de seguranca da JOTABE.',
  ),
  _GraphEdge(
    from: 'company_jotabe',
    to: 'person_ana',
    type: _GraphEdgeType.origin,
    detail: 'Ana esta vinculada diretamente a raiz JOTABE antes da alocacao.',
  ),
  _GraphEdge(
    from: 'contract_portaria',
    to: 'person_ana',
    type: _GraphEdgeType.allocation,
    detail: 'Ana esta alocada no posto de controlador de acesso.',
  ),
  _GraphEdge(
    from: 'company_jotabe',
    to: 'client_horizonte',
    type: _GraphEdgeType.portfolio,
    detail: 'Horizonte Offices integra a carteira da SEDE JOTABE.',
  ),
  _GraphEdge(
    from: 'client_horizonte',
    to: 'contract_adm',
    type: _GraphEdgeType.scope,
    detail: 'A carteira JOTABE desdobra apoio administrativo neste cliente.',
  ),
  _GraphEdge(
    from: 'company_jotabe',
    to: 'person_lucas',
    type: _GraphEdgeType.origin,
    detail: 'Lucas esta vinculado a JOTABE e depois direcionado ao cliente.',
  ),
  _GraphEdge(
    from: 'contract_adm',
    to: 'person_lucas',
    type: _GraphEdgeType.allocation,
    detail: 'Lucas atua como supervisor administrativo neste contrato.',
  ),
  _GraphEdge(
    from: 'contract_adm',
    to: 'person_mila',
    type: _GraphEdgeType.allocation,
    detail: 'Mila entra pela trilha de aprendizagem dentro deste contrato.',
  ),
  _GraphEdge(
    from: 'company_vvg',
    to: 'client_aurora',
    type: _GraphEdgeType.portfolio,
    detail: 'A VVG controla esta carteira hospitalar.',
  ),
  _GraphEdge(
    from: 'client_aurora',
    to: 'contract_governanca',
    type: _GraphEdgeType.scope,
    detail: 'O cliente recebe o contrato hospitalar de governanca e limpeza.',
  ),
  _GraphEdge(
    from: 'company_vvg',
    to: 'person_carla',
    type: _GraphEdgeType.origin,
    detail: 'Carla esta vinculada a VVG antes da alocacao no hospital.',
  ),
  _GraphEdge(
    from: 'contract_governanca',
    to: 'person_carla',
    type: _GraphEdgeType.allocation,
    detail: 'Carla lidera a frente operacional de governanca neste contrato.',
  ),
  _GraphEdge(
    from: 'contract_governanca',
    to: 'person_bruno',
    type: _GraphEdgeType.dismissal,
    detail: 'Bruno saiu deste contrato dentro da janela curta ainda visivel.',
  ),
  _GraphEdge(
    from: 'contract_governanca',
    to: 'person_vera',
    type: _GraphEdgeType.dismissal,
    detail: 'Vera so volta quando a teia abre o recorte historico mais longo.',
  ),
  _GraphEdge(
    from: 'person_carla',
    to: 'company_jotabe',
    type: _GraphEdgeType.history,
    detail: 'Carla teve passagem anterior em uma carteira ligada a JOTABE.',
  ),
];

