part of '../../../app/app.dart';

final _networkGraphContractPreview = _NetworkGraphPayload.fromMap({
  'data': {
    'period': {'preset': '1y', 'from': '2025-01-01', 'to': '2025-12-31'},
    'lanes': [
      'root_company',
      'client_company',
      'contract',
      'position',
      'employee',
    ],
    'nodes': [
      {
        'publicId': 'root_summit_holdings',
        'nodeType': 'root_company',
        'lane': 'root_company',
        'displayName': 'Summit Holdings',
        'subtitle': 'Holding Company',
        'status': 'active',
        'badges': ['3 client companies', '3 visible contracts'],
        'detailSnapshot': {
          'kind': 'root_company',
          'summary':
              'Holding principal do grupo Summit dentro do recorte relacional atual.',
          'activeClientCompanies': 3,
          'activeContracts': 3,
          'activeEmployees': 3,
          'cta': {
            'label': 'Ver grupo completo',
            'targetPublicId': 'root_summit_holdings',
          },
        },
      },
      {
        'publicId': 'root_pioneer_group',
        'nodeType': 'root_company',
        'lane': 'root_company',
        'displayName': 'Pioneer Group',
        'subtitle': 'Holding Company',
        'status': 'active',
        'badges': ['3 client companies', '3 visible contracts'],
        'detailSnapshot': {
          'kind': 'root_company',
          'summary':
              'Raiz Pioneer com leitura combinada de contratos ativos, historicos e relacoes indiretas.',
          'activeClientCompanies': 3,
          'activeContracts': 3,
          'activeEmployees': 3,
          'historicalEmployees': 1,
          'cta': {
            'label': 'Ver grupo completo',
            'targetPublicId': 'root_pioneer_group',
          },
        },
      },
      {
        'publicId': 'client_summit_retail',
        'nodeType': 'client_company',
        'lane': 'client_company',
        'displayName': 'Summit Retail',
        'subtitle': 'LLC',
        'status': 'active',
        'badges': ['1 active contract', '1 active employee'],
        'detailSnapshot': {
          'kind': 'client_company',
          'summary':
              'Operacao de varejo do grupo Summit ligada ao acordo de retail ops.',
          'rootCompanies': ['Summit Holdings'],
          'activeContracts': 1,
          'activeEmployees': 1,
          'cta': {
            'label': 'Abrir empresa cliente',
            'targetPublicId': 'client_summit_retail',
          },
        },
      },
      {
        'publicId': 'client_summit_solutions',
        'nodeType': 'client_company',
        'lane': 'client_company',
        'displayName': 'Summit Solutions',
        'subtitle': 'Inc.',
        'status': 'active',
        'badges': ['2 relevant contracts', 'bridge to Pioneer Services'],
        'detailSnapshot': {
          'kind': 'client_company',
          'summary':
              'Cliente Summit com contrato ativo de TI e acordo expirado ainda relevante.',
          'rootCompanies': ['Summit Holdings'],
          'activeContracts': 2,
          'activeEmployees': 2,
          'indirectConnections': 1,
          'cta': {
            'label': 'Abrir empresa cliente',
            'targetPublicId': 'client_summit_solutions',
          },
        },
      },
      {
        'publicId': 'client_pioneer_services',
        'nodeType': 'client_company',
        'lane': 'client_company',
        'displayName': 'Pioneer Services',
        'subtitle': 'LLC',
        'status': 'active',
        'badges': ['shared delivery context', '2 visible employees'],
        'detailSnapshot': {
          'kind': 'client_company',
          'summary':
              'No central entre Summit e Pioneer, com contexto compartilhado de entrega.',
          'rootCompanies': ['Summit Holdings', 'Pioneer Group'],
          'activeContracts': 2,
          'activeEmployees': 2,
          'indirectConnections': 1,
          'cta': {
            'label': 'Abrir empresa cliente',
            'targetPublicId': 'client_pioneer_services',
          },
        },
      },
      {
        'publicId': 'client_pioneer_retail',
        'nodeType': 'client_company',
        'lane': 'client_company',
        'displayName': 'Pioneer Retail',
        'subtitle': 'Inc.',
        'status': 'active',
        'badges': ['1 historical contract'],
        'detailSnapshot': {
          'kind': 'client_company',
          'summary':
              'Cliente Pioneer com contrato expirado ainda material para leitura de historico.',
          'rootCompanies': ['Pioneer Group'],
          'activeContracts': 1,
          'activeEmployees': 1,
          'cta': {
            'label': 'Abrir empresa cliente',
            'targetPublicId': 'client_pioneer_retail',
          },
        },
      },
      {
        'publicId': 'client_pioneer_tech',
        'nodeType': 'client_company',
        'lane': 'client_company',
        'displayName': 'Pioneer Tech',
        'subtitle': 'LLC',
        'status': 'active',
        'badges': ['supply fallback context'],
        'detailSnapshot': {
          'kind': 'client_company',
          'summary':
              'Cliente tecnico que permanece visivel por conta do supply agreement expirado.',
          'rootCompanies': ['Pioneer Group'],
          'activeContracts': 1,
          'activeEmployees': 1,
          'cta': {
            'label': 'Abrir empresa cliente',
            'targetPublicId': 'client_pioneer_tech',
          },
        },
      },
      {
        'publicId': 'contract_retail_ops',
        'nodeType': 'contract',
        'lane': 'contract',
        'displayName': 'Retail Ops Agreement',
        'subtitle': 'Active',
        'status': 'active',
        'badges': ['1 active employee'],
        'detailSnapshot': {
          'kind': 'contract',
          'summary':
              'Acordo operacional da frente Summit Retail com leitura focada em execucao.',
          'contractStatus': 'active',
          'clientCompanies': ['Summit Retail LLC'],
          'activeEmployees': 1,
          'cta': {
            'label': 'Abrir contrato',
            'targetPublicId': 'contract_retail_ops',
          },
        },
      },
      {
        'publicId': 'contract_it_services',
        'nodeType': 'contract',
        'lane': 'contract',
        'displayName': 'IT Services Contract',
        'subtitle': 'Active',
        'status': 'active',
        'badges': ['2 client companies', '1 active employee'],
        'detailSnapshot': {
          'kind': 'contract',
          'summary':
              'Contrato ativo de TI que cruza Summit Solutions e Pioneer Services.',
          'contractStatus': 'active',
          'clientCompanies': ['Summit Solutions Inc.', 'Pioneer Services LLC'],
          'activeEmployees': 1,
          'cta': {
            'label': 'Abrir contrato',
            'targetPublicId': 'contract_it_services',
          },
        },
      },
      {
        'publicId': 'contract_consulting',
        'nodeType': 'contract',
        'lane': 'contract',
        'displayName': 'Consulting Agreement',
        'subtitle': 'Expired',
        'status': 'expired',
        'badges': ['historical employee context'],
        'detailSnapshot': {
          'kind': 'contract',
          'summary':
              'Contrato expirado que ainda precisa aparecer por manter contexto historico da Sarah.',
          'contractStatus': 'expired',
          'clientCompanies': ['Summit Solutions Inc.'],
          'activeEmployees': 0,
          'historicalEmployees': 1,
          'cta': {
            'label': 'Abrir contrato',
            'targetPublicId': 'contract_consulting',
          },
        },
      },
      {
        'publicId': 'contract_maintenance',
        'nodeType': 'contract',
        'lane': 'contract',
        'displayName': 'Maintenance Contract',
        'subtitle': 'Active',
        'status': 'active',
        'badges': ['2 active employees', 'selected employee anchor'],
        'detailSnapshot': {
          'kind': 'contract',
          'summary':
              'Contrato principal do recorte Pioneer Services, com Sarah como ancora do detalhe lateral.',
          'contractStatus': 'active',
          'clientCompanies': ['Pioneer Services LLC'],
          'activeEmployees': 2,
          'historicalEmployees': 1,
          'cta': {
            'label': 'Abrir contrato',
            'targetPublicId': 'contract_maintenance',
          },
        },
      },
      {
        'publicId': 'contract_supply',
        'nodeType': 'contract',
        'lane': 'contract',
        'displayName': 'Supply Agreement',
        'subtitle': 'Expired',
        'status': 'expired',
        'badges': ['historical retail context'],
        'detailSnapshot': {
          'kind': 'contract',
          'summary':
              'Acordo expirado que explica a permanencia de Pioneer Retail e Pioneer Tech no recorte.',
          'contractStatus': 'expired',
          'clientCompanies': ['Pioneer Retail Inc.', 'Pioneer Tech LLC'],
          'activeEmployees': 1,
          'cta': {
            'label': 'Abrir contrato',
            'targetPublicId': 'contract_supply',
          },
        },
      },
      {
        'publicId': 'position_controlador_acesso',
        'nodeType': 'position',
        'lane': 'position',
        'displayName': 'Controlador de Acesso',
        'subtitle': 'Posto diurno',
        'status': 'active',
        'badges': ['Retail Ops Agreement', '2 active employees'],
        'detailSnapshot': {
          'kind': 'position',
          'summary':
              'Posto de controle de acesso vinculado a operacoes presenciais.',
          'contractStatus': 'active',
          'clientCompanies': ['Summit Retail LLC'],
          'activeEmployees': 2,
          'cta': {
            'label': 'Abrir posicao',
            'targetPublicId': 'position_controlador_acesso',
          },
          'contract': 'Retail Ops Agreement',
          'scale': '5x2',
          'shift': 'Diurno',
          'statusLabel': 'Active',
          'location': 'Seattle, WA',
        },
      },
      {
        'publicId': 'position_suporte_ti',
        'nodeType': 'position',
        'lane': 'position',
        'displayName': 'Suporte TI N2',
        'subtitle': 'Infraestrutura',
        'status': 'active',
        'badges': ['IT Services Contract'],
        'detailSnapshot': {
          'kind': 'position',
          'summary':
              'Posicao tecnica compartilhada entre Summit Solutions e Pioneer Services.',
          'contractStatus': 'active',
          'clientCompanies': ['Summit Solutions Inc.', 'Pioneer Services LLC'],
          'activeEmployees': 2,
          'cta': {
            'label': 'Abrir posicao',
            'targetPublicId': 'position_suporte_ti',
          },
          'contract': 'IT Services Contract',
          'scale': '5x2',
          'shift': 'Comercial',
          'statusLabel': 'Active',
          'location': 'Austin, TX',
        },
      },
      {
        'publicId': 'position_analista_consulting',
        'nodeType': 'position',
        'lane': 'position',
        'displayName': 'Analista de Projetos',
        'subtitle': 'Encerrada',
        'status': 'ended',
        'badges': ['Consulting Agreement'],
        'detailSnapshot': {
          'kind': 'position',
          'summary':
              'Posicao encerrada que preserva contexto historico do contrato de consulting.',
          'contractStatus': 'expired',
          'clientCompanies': ['Summit Solutions Inc.'],
          'activeEmployees': 0,
          'historicalEmployees': 1,
          'cta': {
            'label': 'Abrir posicao',
            'targetPublicId': 'position_analista_consulting',
          },
          'contract': 'Consulting Agreement',
          'scale': 'Projeto',
          'shift': 'Sob demanda',
          'statusLabel': 'Ended',
          'location': 'Remote',
        },
      },
      {
        'publicId': 'position_limpeza_5x2',
        'nodeType': 'position',
        'lane': 'position',
        'displayName': 'Limpeza 5x2',
        'subtitle': 'Manha',
        'status': 'active',
        'badges': ['Maintenance Contract'],
        'detailSnapshot': {
          'kind': 'position',
          'summary':
              'Posto de limpeza de segunda a sexta no contrato de maintenance.',
          'contractStatus': 'active',
          'clientCompanies': ['Pioneer Services LLC'],
          'activeEmployees': 3,
          'cta': {
            'label': 'Abrir posicao',
            'targetPublicId': 'position_limpeza_5x2',
          },
          'contract': 'Maintenance Contract',
          'scale': '5x2',
          'shift': 'Manha',
          'statusLabel': 'Active',
          'location': 'Chicago, IL',
        },
      },
      {
        'publicId': 'position_limpeza_6x1',
        'nodeType': 'position',
        'lane': 'position',
        'displayName': 'Limpeza 6X1',
        'subtitle': 'Tarde',
        'status': 'active',
        'badges': ['Maintenance Contract'],
        'detailSnapshot': {
          'kind': 'position',
          'summary': 'Posto de limpeza 6x1 com cobertura de fim de semana.',
          'contractStatus': 'active',
          'clientCompanies': ['Pioneer Services LLC'],
          'activeEmployees': 2,
          'cta': {
            'label': 'Abrir posicao',
            'targetPublicId': 'position_limpeza_6x1',
          },
          'contract': 'Maintenance Contract',
          'scale': '6X1',
          'shift': 'Tarde',
          'statusLabel': 'Active',
          'location': 'Chicago, IL',
        },
      },
      {
        'publicId': 'position_limpeza_12x36',
        'nodeType': 'position',
        'lane': 'position',
        'displayName': 'Limpeza 12x36',
        'subtitle': 'Noturno',
        'status': 'active',
        'badges': ['Maintenance Contract'],
        'detailSnapshot': {
          'kind': 'position',
          'summary':
              'Escala 12x36 para cobertura noturna do contrato de maintenance.',
          'contractStatus': 'active',
          'clientCompanies': ['Pioneer Services LLC'],
          'activeEmployees': 2,
          'cta': {
            'label': 'Abrir posicao',
            'targetPublicId': 'position_limpeza_12x36',
          },
          'contract': 'Maintenance Contract',
          'scale': '12x36',
          'shift': 'Noturno',
          'statusLabel': 'Active',
          'location': 'Chicago, IL',
        },
      },
      {
        'publicId': 'position_vigia',
        'nodeType': 'position',
        'lane': 'position',
        'displayName': 'Vigia',
        'subtitle': 'Ronda',
        'status': 'active',
        'badges': ['Maintenance Contract'],
        'detailSnapshot': {
          'kind': 'position',
          'summary':
              'Posto de vigia com ronda presencial e acompanhamento de acesso.',
          'contractStatus': 'active',
          'clientCompanies': ['Pioneer Services LLC'],
          'activeEmployees': 2,
          'cta': {'label': 'Abrir posicao', 'targetPublicId': 'position_vigia'},
          'contract': 'Maintenance Contract',
          'scale': '12x36',
          'shift': 'Noite',
          'statusLabel': 'Active',
          'location': 'Chicago, IL',
        },
      },
      {
        'publicId': 'position_garcom',
        'nodeType': 'position',
        'lane': 'position',
        'displayName': 'Garcom',
        'subtitle': 'Eventos',
        'status': 'active',
        'badges': ['Supply Agreement'],
        'detailSnapshot': {
          'kind': 'position',
          'summary':
              'Posicao operacional de atendimento preservada no recorte do supply agreement.',
          'contractStatus': 'active',
          'clientCompanies': ['Pioneer Retail Inc.', 'Pioneer Tech LLC'],
          'activeEmployees': 2,
          'cta': {
            'label': 'Abrir posicao',
            'targetPublicId': 'position_garcom',
          },
          'contract': 'Supply Agreement',
          'scale': 'Evento',
          'shift': 'Variavel',
          'statusLabel': 'Active',
          'location': 'Denver, CO',
        },
      },
      {
        'publicId': 'position_estoquista',
        'nodeType': 'position',
        'lane': 'position',
        'displayName': 'Estoquista',
        'subtitle': 'Desativada',
        'status': 'deactivated',
        'badges': ['Supply Agreement'],
        'detailSnapshot': {
          'kind': 'position',
          'summary':
              'Posto desativado mantido para leitura historica do contrato de supply.',
          'contractStatus': 'expired',
          'clientCompanies': ['Pioneer Tech LLC'],
          'activeEmployees': 0,
          'historicalEmployees': 1,
          'cta': {
            'label': 'Abrir posicao',
            'targetPublicId': 'position_estoquista',
          },
          'contract': 'Supply Agreement',
          'scale': '6x1',
          'shift': 'Tarde',
          'statusLabel': 'Deactivated',
          'location': 'Denver, CO',
        },
      },
      {
        'publicId': 'employee_jessica_lee',
        'nodeType': 'employee',
        'lane': 'employee',
        'displayName': 'Jessica Lee',
        'subtitle': 'Project Manager',
        'status': 'active',
        'badges': ['Retail Ops Agreement'],
        'detailSnapshot': {
          'kind': 'employee',
          'summary':
              'Gestora operacional da frente Summit Retail dentro do acordo de retail ops.',
          'activeContracts': 1,
          'cta': {
            'label': 'Abrir pessoa',
            'targetPublicId': 'employee_jessica_lee',
          },
          'employeeId': 'EMP-09214',
          'email': 'jessica.lee@summitretail.com',
          'phone': '+1 (555) 830-2211',
          'department': 'Operations',
          'manager': 'Karen Miles',
          'clientCompany': 'Summit Retail LLC',
          'contract': 'Retail Ops Agreement',
          'statusLabel': 'Active',
          'startDate': 'Mar 04, 2021',
          'location': 'Seattle, WA',
        },
      },
      {
        'publicId': 'employee_michael_chen',
        'nodeType': 'employee',
        'lane': 'employee',
        'displayName': 'Michael Chen',
        'subtitle': 'IT Specialist',
        'status': 'active',
        'badges': ['IT Services Contract'],
        'detailSnapshot': {
          'kind': 'employee',
          'summary':
              'Especialista de TI alocado no contrato compartilhado entre Summit Solutions e Pioneer Services.',
          'activeContracts': 1,
          'cta': {
            'label': 'Abrir pessoa',
            'targetPublicId': 'employee_michael_chen',
          },
          'employeeId': 'EMP-09772',
          'email': 'michael.chen@summitsolutions.com',
          'phone': '+1 (555) 712-0092',
          'department': 'Infrastructure',
          'manager': 'Rachel Kim',
          'clientCompany': 'Summit Solutions Inc.',
          'contract': 'IT Services Contract',
          'statusLabel': 'Active',
          'startDate': 'Jul 18, 2022',
          'location': 'Austin, TX',
        },
      },
      {
        'publicId': 'employee_sarah_johnson',
        'nodeType': 'employee',
        'lane': 'employee',
        'displayName': 'Sarah Johnson',
        'subtitle': 'Senior Analyst',
        'status': 'active',
        'badges': ['Maintenance Contract', 'historical consulting context'],
        'detailSnapshot': {
          'kind': 'employee',
          'summary':
              'Analista senior com vinculo ativo em maintenance e passagem historica por consulting.',
          'activeContracts': 1,
          'historicalContracts': 1,
          'cta': {
            'label': 'View Full Profile',
            'targetPublicId': 'employee_sarah_johnson',
          },
          'employeeId': 'EMP-10432',
          'email': 'sarah.johnson@pioneerservices.com',
          'phone': '+1 (555) 234-5678',
          'department': 'Analytics',
          'manager': 'David Williams',
          'clientCompany': 'Pioneer Services LLC',
          'contract': 'Maintenance Contract',
          'statusLabel': 'Active',
          'startDate': 'Jan 15, 2022',
          'location': 'Chicago, IL',
        },
      },
      {
        'publicId': 'employee_david_williams',
        'nodeType': 'employee',
        'lane': 'employee',
        'displayName': 'David Williams',
        'subtitle': 'Account Manager',
        'status': 'active',
        'badges': ['Maintenance Contract'],
        'detailSnapshot': {
          'kind': 'employee',
          'summary':
              'Responsavel pela conta Pioneer Services dentro do contrato de maintenance.',
          'activeContracts': 1,
          'cta': {
            'label': 'Abrir pessoa',
            'targetPublicId': 'employee_david_williams',
          },
          'employeeId': 'EMP-10501',
          'email': 'david.williams@pioneerservices.com',
          'phone': '+1 (555) 778-1994',
          'department': 'Accounts',
          'manager': 'Laura Bennett',
          'clientCompany': 'Pioneer Services LLC',
          'contract': 'Maintenance Contract',
          'statusLabel': 'Active',
          'startDate': 'Nov 02, 2020',
          'location': 'Chicago, IL',
        },
      },
      {
        'publicId': 'employee_emily_davis',
        'nodeType': 'employee',
        'lane': 'employee',
        'displayName': 'Emily Davis',
        'subtitle': 'Operations Lead',
        'status': 'active',
        'badges': ['Supply Agreement'],
        'detailSnapshot': {
          'kind': 'employee',
          'summary':
              'Lider operacional preservada no recorte por conta do supply agreement expirado.',
          'activeContracts': 1,
          'cta': {
            'label': 'Abrir pessoa',
            'targetPublicId': 'employee_emily_davis',
          },
          'employeeId': 'EMP-10618',
          'email': 'emily.davis@pioneertech.com',
          'phone': '+1 (555) 448-9011',
          'department': 'Operations',
          'manager': 'David Williams',
          'clientCompany': 'Pioneer Tech LLC',
          'contract': 'Supply Agreement',
          'statusLabel': 'Active',
          'startDate': 'May 10, 2023',
          'location': 'Denver, CO',
        },
      },
      {
        'publicId': 'employee_ana_costa',
        'nodeType': 'employee',
        'lane': 'employee',
        'displayName': 'Ana Costa',
        'subtitle': 'Auxiliar de Limpeza',
        'status': 'active',
        'badges': ['Limpeza 5x2'],
        'detailSnapshot': {
          'kind': 'employee',
          'summary':
              'Profissional alocada na escala de limpeza 5x2 do contrato de maintenance.',
          'activeContracts': 1,
          'cta': {
            'label': 'Abrir pessoa',
            'targetPublicId': 'employee_ana_costa',
          },
          'employeeId': 'EMP-10720',
          'email': 'ana.costa@pioneerservices.com',
          'phone': '+1 (555) 311-4401',
          'department': 'Facilities',
          'manager': 'David Williams',
          'clientCompany': 'Pioneer Services LLC',
          'contract': 'Maintenance Contract',
          'position': 'Limpeza 5x2',
          'statusLabel': 'Active',
          'startDate': 'Feb 12, 2024',
          'location': 'Chicago, IL',
        },
      },
      {
        'publicId': 'employee_bruno_rocha',
        'nodeType': 'employee',
        'lane': 'employee',
        'displayName': 'Bruno Rocha',
        'subtitle': 'Auxiliar de Limpeza',
        'status': 'active',
        'badges': ['Limpeza 6x1'],
        'detailSnapshot': {
          'kind': 'employee',
          'summary':
              'Cobertura de limpeza 6x1 para areas comuns no contrato de maintenance.',
          'activeContracts': 1,
          'cta': {
            'label': 'Abrir pessoa',
            'targetPublicId': 'employee_bruno_rocha',
          },
          'employeeId': 'EMP-10731',
          'email': 'bruno.rocha@pioneerservices.com',
          'phone': '+1 (555) 311-4402',
          'department': 'Facilities',
          'manager': 'David Williams',
          'clientCompany': 'Pioneer Services LLC',
          'contract': 'Maintenance Contract',
          'position': 'Limpeza 6x1',
          'statusLabel': 'Active',
          'startDate': 'Apr 01, 2024',
          'location': 'Chicago, IL',
        },
      },
      {
        'publicId': 'employee_carla_mendes',
        'nodeType': 'employee',
        'lane': 'employee',
        'displayName': 'Carla Mendes',
        'subtitle': 'Auxiliar de Limpeza',
        'status': 'active',
        'badges': ['Limpeza 12x36'],
        'detailSnapshot': {
          'kind': 'employee',
          'summary':
              'Escala noturna 12x36 vinculada ao contrato de maintenance.',
          'activeContracts': 1,
          'cta': {
            'label': 'Abrir pessoa',
            'targetPublicId': 'employee_carla_mendes',
          },
          'employeeId': 'EMP-10744',
          'email': 'carla.mendes@pioneerservices.com',
          'phone': '+1 (555) 311-4403',
          'department': 'Facilities',
          'manager': 'David Williams',
          'clientCompany': 'Pioneer Services LLC',
          'contract': 'Maintenance Contract',
          'position': 'Limpeza 12x36',
          'statusLabel': 'Active',
          'startDate': 'Apr 16, 2024',
          'location': 'Chicago, IL',
        },
      },
      {
        'publicId': 'employee_rafael_lima',
        'nodeType': 'employee',
        'lane': 'employee',
        'displayName': 'Rafael Lima',
        'subtitle': 'Vigia',
        'status': 'active',
        'badges': ['Vigia'],
        'detailSnapshot': {
          'kind': 'employee',
          'summary':
              'Vigia alocado em ronda noturna no contrato de maintenance.',
          'activeContracts': 1,
          'cta': {
            'label': 'Abrir pessoa',
            'targetPublicId': 'employee_rafael_lima',
          },
          'employeeId': 'EMP-10757',
          'email': 'rafael.lima@pioneerservices.com',
          'phone': '+1 (555) 311-4404',
          'department': 'Security',
          'manager': 'David Williams',
          'clientCompany': 'Pioneer Services LLC',
          'contract': 'Maintenance Contract',
          'position': 'Vigia',
          'statusLabel': 'Active',
          'startDate': 'Jan 22, 2024',
          'location': 'Chicago, IL',
        },
      },
      {
        'publicId': 'employee_priscila_nunes',
        'nodeType': 'employee',
        'lane': 'employee',
        'displayName': 'Priscila Nunes',
        'subtitle': 'Controladora de Acesso',
        'status': 'active',
        'badges': ['Controlador de Acesso'],
        'detailSnapshot': {
          'kind': 'employee',
          'summary': 'Controle de acesso para operacao Summit Retail.',
          'activeContracts': 1,
          'cta': {
            'label': 'Abrir pessoa',
            'targetPublicId': 'employee_priscila_nunes',
          },
          'employeeId': 'EMP-10763',
          'email': 'priscila.nunes@summitretail.com',
          'phone': '+1 (555) 311-4405',
          'department': 'Security',
          'manager': 'Karen Miles',
          'clientCompany': 'Summit Retail LLC',
          'contract': 'Retail Ops Agreement',
          'position': 'Controlador de Acesso',
          'statusLabel': 'Active',
          'startDate': 'Jun 03, 2024',
          'location': 'Seattle, WA',
        },
      },
      {
        'publicId': 'employee_joao_alves',
        'nodeType': 'employee',
        'lane': 'employee',
        'displayName': 'Joao Alves',
        'subtitle': 'Garcom',
        'status': 'active',
        'badges': ['Garcom'],
        'detailSnapshot': {
          'kind': 'employee',
          'summary': 'Atendimento operacional em eventos do supply agreement.',
          'activeContracts': 1,
          'cta': {
            'label': 'Abrir pessoa',
            'targetPublicId': 'employee_joao_alves',
          },
          'employeeId': 'EMP-10778',
          'email': 'joao.alves@pioneertech.com',
          'phone': '+1 (555) 311-4406',
          'department': 'Hospitality',
          'manager': 'Emily Davis',
          'clientCompany': 'Pioneer Tech LLC',
          'contract': 'Supply Agreement',
          'position': 'Garcom',
          'statusLabel': 'Active',
          'startDate': 'Aug 09, 2024',
          'location': 'Denver, CO',
        },
      },
      {
        'publicId': 'employee_marta_silva',
        'nodeType': 'employee',
        'lane': 'employee',
        'displayName': 'Marta Silva',
        'subtitle': 'Estoquista',
        'status': 'dismissed',
        'badges': ['Estoquista'],
        'detailSnapshot': {
          'kind': 'employee',
          'summary':
              'Vinculo desligado preservado para historico do supply agreement.',
          'activeContracts': 0,
          'historicalContracts': 1,
          'cta': {
            'label': 'Abrir pessoa',
            'targetPublicId': 'employee_marta_silva',
          },
          'employeeId': 'EMP-09888',
          'email': 'marta.silva@pioneertech.com',
          'phone': '+1 (555) 311-4407',
          'department': 'Logistics',
          'manager': 'Emily Davis',
          'clientCompany': 'Pioneer Tech LLC',
          'contract': 'Supply Agreement',
          'position': 'Estoquista',
          'statusLabel': 'Dismissed',
          'startDate': 'Jan 14, 2023',
          'location': 'Denver, CO',
        },
      },
    ],
    'edges': [
      {
        'publicId': 'edge_root_historical',
        'fromPublicId': 'root_summit_holdings',
        'toPublicId': 'root_pioneer_group',
        'relationshipKind': 'portfolio_history',
        'relationshipState': 'historical',
        'periodStart': '2023-01-01',
        'periodEnd': '2024-12-31',
        'metadata': {'label': 'historical portfolio overlap'},
      },
      {
        'publicId': 'edge_root_summit_retail',
        'fromPublicId': 'root_summit_holdings',
        'toPublicId': 'client_summit_retail',
        'relationshipKind': 'client_membership',
        'relationshipState': 'active',
        'periodStart': '2024-01-01',
        'periodEnd': null,
        'metadata': {},
      },
      {
        'publicId': 'edge_root_summit_solutions',
        'fromPublicId': 'root_summit_holdings',
        'toPublicId': 'client_summit_solutions',
        'relationshipKind': 'client_membership',
        'relationshipState': 'active',
        'periodStart': '2024-01-01',
        'periodEnd': null,
        'metadata': {},
      },
      {
        'publicId': 'edge_root_pioneer_services_from_summit',
        'fromPublicId': 'root_summit_holdings',
        'toPublicId': 'client_pioneer_services',
        'relationshipKind': 'shared_delivery_membership',
        'relationshipState': 'active',
        'periodStart': '2024-06-01',
        'periodEnd': null,
        'metadata': {'label': 'shared delivery context'},
      },
      {
        'publicId': 'edge_root_pioneer_services_from_pioneer',
        'fromPublicId': 'root_pioneer_group',
        'toPublicId': 'client_pioneer_services',
        'relationshipKind': 'client_membership',
        'relationshipState': 'active',
        'periodStart': '2024-01-01',
        'periodEnd': null,
        'metadata': {},
      },
      {
        'publicId': 'edge_root_pioneer_retail',
        'fromPublicId': 'root_pioneer_group',
        'toPublicId': 'client_pioneer_retail',
        'relationshipKind': 'client_membership',
        'relationshipState': 'active',
        'periodStart': '2024-01-01',
        'periodEnd': null,
        'metadata': {},
      },
      {
        'publicId': 'edge_root_pioneer_tech',
        'fromPublicId': 'root_pioneer_group',
        'toPublicId': 'client_pioneer_tech',
        'relationshipKind': 'client_membership',
        'relationshipState': 'active',
        'periodStart': '2024-01-01',
        'periodEnd': null,
        'metadata': {},
      },
      {
        'publicId': 'edge_client_bridge',
        'fromPublicId': 'client_summit_solutions',
        'toPublicId': 'client_pioneer_services',
        'relationshipKind': 'indirect_association',
        'relationshipState': 'indirect',
        'periodStart': '2025-01-01',
        'periodEnd': null,
        'metadata': {'label': 'shared delivery context'},
      },
      {
        'publicId': 'edge_retail_contract',
        'fromPublicId': 'client_summit_retail',
        'toPublicId': 'contract_retail_ops',
        'relationshipKind': 'contract_allocation',
        'relationshipState': 'active',
        'periodStart': '2024-02-01',
        'periodEnd': null,
        'metadata': {},
      },
      {
        'publicId': 'edge_it_contract_summit',
        'fromPublicId': 'client_summit_solutions',
        'toPublicId': 'contract_it_services',
        'relationshipKind': 'contract_allocation',
        'relationshipState': 'active',
        'periodStart': '2024-03-01',
        'periodEnd': null,
        'metadata': {},
      },
      {
        'publicId': 'edge_consulting_contract',
        'fromPublicId': 'client_summit_solutions',
        'toPublicId': 'contract_consulting',
        'relationshipKind': 'contract_allocation',
        'relationshipState': 'historical',
        'periodStart': '2023-01-01',
        'periodEnd': '2024-06-30',
        'metadata': {'label': 'expired consulting scope'},
      },
      {
        'publicId': 'edge_it_contract_pioneer',
        'fromPublicId': 'client_pioneer_services',
        'toPublicId': 'contract_it_services',
        'relationshipKind': 'contract_allocation',
        'relationshipState': 'active',
        'periodStart': '2024-03-01',
        'periodEnd': null,
        'metadata': {},
      },
      {
        'publicId': 'edge_maintenance_contract',
        'fromPublicId': 'client_pioneer_services',
        'toPublicId': 'contract_maintenance',
        'relationshipKind': 'contract_allocation',
        'relationshipState': 'active',
        'periodStart': '2024-04-15',
        'periodEnd': null,
        'metadata': {},
      },
      {
        'publicId': 'edge_supply_contract_retail',
        'fromPublicId': 'client_pioneer_retail',
        'toPublicId': 'contract_supply',
        'relationshipKind': 'contract_allocation',
        'relationshipState': 'historical',
        'periodStart': '2023-03-01',
        'periodEnd': '2024-11-30',
        'metadata': {'label': 'expired supply scope'},
      },
      {
        'publicId': 'edge_supply_contract_tech',
        'fromPublicId': 'client_pioneer_tech',
        'toPublicId': 'contract_supply',
        'relationshipKind': 'contract_allocation',
        'relationshipState': 'active',
        'periodStart': '2024-09-01',
        'periodEnd': null,
        'metadata': {'label': 'support continuation'},
      },
      {
        'publicId': 'edge_contract_bridge_one',
        'fromPublicId': 'contract_consulting',
        'toPublicId': 'contract_maintenance',
        'relationshipKind': 'indirect_association',
        'relationshipState': 'indirect',
        'periodStart': '2025-01-01',
        'periodEnd': null,
        'metadata': {'label': 'employee history overlap'},
      },
      {
        'publicId': 'edge_contract_bridge_two',
        'fromPublicId': 'contract_maintenance',
        'toPublicId': 'contract_supply',
        'relationshipKind': 'indirect_association',
        'relationshipState': 'indirect',
        'periodStart': '2025-01-01',
        'periodEnd': null,
        'metadata': {'label': 'shared retail account'},
      },
      {
        'publicId': 'edge_contract_position_access',
        'fromPublicId': 'contract_retail_ops',
        'toPublicId': 'position_controlador_acesso',
        'relationshipKind': 'position_scope',
        'relationshipState': 'active',
        'periodStart': '2024-02-01',
        'periodEnd': null,
        'metadata': {'label': 'access control scope'},
      },
      {
        'publicId': 'edge_contract_position_suporte',
        'fromPublicId': 'contract_it_services',
        'toPublicId': 'position_suporte_ti',
        'relationshipKind': 'position_scope',
        'relationshipState': 'active',
        'periodStart': '2024-03-01',
        'periodEnd': null,
        'metadata': {'label': 'technical support scope'},
      },
      {
        'publicId': 'edge_contract_position_consulting',
        'fromPublicId': 'contract_consulting',
        'toPublicId': 'position_analista_consulting',
        'relationshipKind': 'position_scope',
        'relationshipState': 'historical',
        'periodStart': '2023-01-01',
        'periodEnd': '2024-06-30',
        'metadata': {'label': 'closed project role'},
      },
      {
        'publicId': 'edge_contract_position_limpeza_5x2',
        'fromPublicId': 'contract_maintenance',
        'toPublicId': 'position_limpeza_5x2',
        'relationshipKind': 'position_scope',
        'relationshipState': 'active',
        'periodStart': '2024-04-15',
        'periodEnd': null,
        'metadata': {'label': 'cleaning 5x2'},
      },
      {
        'publicId': 'edge_contract_position_limpeza_6x1',
        'fromPublicId': 'contract_maintenance',
        'toPublicId': 'position_limpeza_6x1',
        'relationshipKind': 'position_scope',
        'relationshipState': 'active',
        'periodStart': '2024-04-15',
        'periodEnd': null,
        'metadata': {'label': 'cleaning 6x1'},
      },
      {
        'publicId': 'edge_contract_position_limpeza_12x36',
        'fromPublicId': 'contract_maintenance',
        'toPublicId': 'position_limpeza_12x36',
        'relationshipKind': 'position_scope',
        'relationshipState': 'active',
        'periodStart': '2024-04-15',
        'periodEnd': null,
        'metadata': {'label': 'cleaning 12x36'},
      },
      {
        'publicId': 'edge_contract_position_vigia',
        'fromPublicId': 'contract_maintenance',
        'toPublicId': 'position_vigia',
        'relationshipKind': 'position_scope',
        'relationshipState': 'active',
        'periodStart': '2024-04-15',
        'periodEnd': null,
        'metadata': {'label': 'security watch'},
      },
      {
        'publicId': 'edge_contract_position_garcom',
        'fromPublicId': 'contract_supply',
        'toPublicId': 'position_garcom',
        'relationshipKind': 'position_scope',
        'relationshipState': 'active',
        'periodStart': '2024-09-01',
        'periodEnd': null,
        'metadata': {'label': 'event support'},
      },
      {
        'publicId': 'edge_contract_position_estoquista',
        'fromPublicId': 'contract_supply',
        'toPublicId': 'position_estoquista',
        'relationshipKind': 'position_scope',
        'relationshipState': 'historical',
        'periodStart': '2023-03-01',
        'periodEnd': '2024-11-30',
        'metadata': {'label': 'deactivated stock role'},
      },
      {
        'publicId': 'edge_position_employee_jessica',
        'fromPublicId': 'position_controlador_acesso',
        'toPublicId': 'employee_jessica_lee',
        'relationshipKind': 'employment_link',
        'relationshipState': 'active',
        'periodStart': '2024-02-10',
        'periodEnd': null,
        'metadata': {'label': 'current allocation'},
      },
      {
        'publicId': 'edge_position_employee_priscila',
        'fromPublicId': 'position_controlador_acesso',
        'toPublicId': 'employee_priscila_nunes',
        'relationshipKind': 'employment_link',
        'relationshipState': 'active',
        'periodStart': '2024-06-03',
        'periodEnd': null,
        'metadata': {'label': 'current allocation'},
      },
      {
        'publicId': 'edge_position_employee_michael',
        'fromPublicId': 'position_suporte_ti',
        'toPublicId': 'employee_michael_chen',
        'relationshipKind': 'employment_link',
        'relationshipState': 'active',
        'periodStart': '2024-03-18',
        'periodEnd': null,
        'metadata': {'label': 'current allocation'},
      },
      {
        'publicId': 'edge_position_employee_sarah_historical',
        'fromPublicId': 'position_analista_consulting',
        'toPublicId': 'employee_sarah_johnson',
        'relationshipKind': 'employment_link',
        'relationshipState': 'historical',
        'periodStart': '2023-04-01',
        'periodEnd': '2024-02-29',
        'metadata': {'label': 'previous allocation'},
      },
      {
        'publicId': 'edge_position_employee_sarah_active',
        'fromPublicId': 'position_limpeza_5x2',
        'toPublicId': 'employee_sarah_johnson',
        'relationshipKind': 'employment_link',
        'relationshipState': 'active',
        'periodStart': '2024-03-01',
        'periodEnd': null,
        'metadata': {'label': 'current allocation'},
      },
      {
        'publicId': 'edge_position_employee_david',
        'fromPublicId': 'position_vigia',
        'toPublicId': 'employee_david_williams',
        'relationshipKind': 'employment_link',
        'relationshipState': 'active',
        'periodStart': '2024-04-01',
        'periodEnd': null,
        'metadata': {'label': 'account owner'},
      },
      {
        'publicId': 'edge_position_employee_ana',
        'fromPublicId': 'position_limpeza_5x2',
        'toPublicId': 'employee_ana_costa',
        'relationshipKind': 'employment_link',
        'relationshipState': 'active',
        'periodStart': '2024-02-12',
        'periodEnd': null,
        'metadata': {'label': 'current allocation'},
      },
      {
        'publicId': 'edge_position_employee_bruno',
        'fromPublicId': 'position_limpeza_6x1',
        'toPublicId': 'employee_bruno_rocha',
        'relationshipKind': 'employment_link',
        'relationshipState': 'active',
        'periodStart': '2024-04-01',
        'periodEnd': null,
        'metadata': {'label': 'current allocation'},
      },
      {
        'publicId': 'edge_position_employee_carla',
        'fromPublicId': 'position_limpeza_12x36',
        'toPublicId': 'employee_carla_mendes',
        'relationshipKind': 'employment_link',
        'relationshipState': 'active',
        'periodStart': '2024-04-16',
        'periodEnd': null,
        'metadata': {'label': 'current allocation'},
      },
      {
        'publicId': 'edge_position_employee_rafael',
        'fromPublicId': 'position_vigia',
        'toPublicId': 'employee_rafael_lima',
        'relationshipKind': 'employment_link',
        'relationshipState': 'active',
        'periodStart': '2024-01-22',
        'periodEnd': null,
        'metadata': {'label': 'current allocation'},
      },
      {
        'publicId': 'edge_position_employee_emily',
        'fromPublicId': 'position_garcom',
        'toPublicId': 'employee_emily_davis',
        'relationshipKind': 'employment_link',
        'relationshipState': 'active',
        'periodStart': '2024-09-10',
        'periodEnd': null,
        'metadata': {'label': 'operations lead'},
      },
      {
        'publicId': 'edge_position_employee_joao',
        'fromPublicId': 'position_garcom',
        'toPublicId': 'employee_joao_alves',
        'relationshipKind': 'employment_link',
        'relationshipState': 'active',
        'periodStart': '2024-08-09',
        'periodEnd': null,
        'metadata': {'label': 'event support'},
      },
      {
        'publicId': 'edge_position_employee_marta',
        'fromPublicId': 'position_estoquista',
        'toPublicId': 'employee_marta_silva',
        'relationshipKind': 'employment_link',
        'relationshipState': 'historical',
        'periodStart': '2023-03-01',
        'periodEnd': '2024-11-30',
        'metadata': {'label': 'dismissed allocation'},
      },
    ],
    'filters': {
      'search': '',
      'applied': {
        'periodPreset': '1y',
        'rootCompanyPublicIds': [],
        'clientCompanyPublicIds': [],
        'contractStatuses': ['active', 'expired'],
        'employeeStatuses': ['active', 'dismissed'],
        'includeHistorical': true,
        'includeIndirect': true,
      },
      'available': {
        'periodPresets': ['6m', '1y', '2y', 'all'],
        'rootCompanies': [
          {'publicId': 'root_summit_holdings', 'label': 'Summit Holdings'},
          {'publicId': 'root_pioneer_group', 'label': 'Pioneer Group'},
        ],
        'clientCompanies': [
          {'publicId': 'client_summit_retail', 'label': 'Summit Retail LLC'},
          {
            'publicId': 'client_summit_solutions',
            'label': 'Summit Solutions Inc.',
          },
          {
            'publicId': 'client_pioneer_services',
            'label': 'Pioneer Services LLC',
          },
          {'publicId': 'client_pioneer_retail', 'label': 'Pioneer Retail Inc.'},
          {'publicId': 'client_pioneer_tech', 'label': 'Pioneer Tech LLC'},
        ],
        'contractStatuses': ['active', 'expired'],
        'employeeStatuses': ['active', 'dismissed'],
        'relationshipStates': ['active', 'historical', 'indirect'],
      },
    },
    'legend': {
      'relationshipStates': [
        {'value': 'active', 'label': 'Active Relationship'},
        {'value': 'historical', 'label': 'Historical Relationship'},
        {'value': 'indirect', 'label': 'Indirect Relationship'},
      ],
    },
    'focus': {
      'selectedNodePublicId': 'employee_sarah_johnson',
      'hoveredNodePublicId': null,
      'viewportAnchorPublicId': 'employee_sarah_johnson',
    },
  },
  'meta': {'traceId': 'req_01hnetworkcontractpreview0002'},
});
