part of '../../../app/app.dart';

final _networkGraphContractPreview = _NetworkGraphPayload.fromMap({
  'data': {
    'period': {'preset': '1y', 'from': '2025-01-01', 'to': '2025-12-31'},
    'lanes': ['root_company', 'client_company', 'contract', 'employee'],
    'nodes': [
      {
        'publicId': 'root_summit_holdings',
        'nodeType': 'root_company',
        'lane': 'root_company',
        'displayName': 'Summit Holdings',
        'subtitle': 'Holding Company',
        'status': 'active',
        'badges': ['3 client companies', '3 visible contracts'],
        'detailSnapshot': {
          'kind': 'root_company',
          'summary':
              'Holding principal do grupo Summit dentro do recorte relacional atual.',
          'activeClientCompanies': 3,
          'activeContracts': 3,
          'activeEmployees': 3,
          'cta': {
            'label': 'Ver grupo completo',
            'targetPublicId': 'root_summit_holdings',
          },
        },
      },
      {
        'publicId': 'root_pioneer_group',
        'nodeType': 'root_company',
        'lane': 'root_company',
        'displayName': 'Pioneer Group',
        'subtitle': 'Holding Company',
        'status': 'active',
        'badges': ['3 client companies', '3 visible contracts'],
        'detailSnapshot': {
          'kind': 'root_company',
          'summary':
              'Raiz Pioneer com leitura combinada de contratos ativos, historicos e relacoes indiretas.',
          'activeClientCompanies': 3,
          'activeContracts': 3,
          'activeEmployees': 3,
          'historicalEmployees': 1,
          'cta': {
            'label': 'Ver grupo completo',
            'targetPublicId': 'root_pioneer_group',
          },
        },
      },
      {
        'publicId': 'client_summit_retail',
        'nodeType': 'client_company',
        'lane': 'client_company',
        'displayName': 'Summit Retail',
        'subtitle': 'LLC',
        'status': 'active',
        'badges': ['1 active contract', '1 active employee'],
        'detailSnapshot': {
          'kind': 'client_company',
          'summary':
              'Operacao de varejo do grupo Summit ligada ao acordo de retail ops.',
          'rootCompanies': ['Summit Holdings'],
          'activeContracts': 1,
          'activeEmployees': 1,
          'cta': {
            'label': 'Abrir empresa cliente',
            'targetPublicId': 'client_summit_retail',
          },
        },
      },
      {
        'publicId': 'client_summit_solutions',
        'nodeType': 'client_company',
        'lane': 'client_company',
        'displayName': 'Summit Solutions',
        'subtitle': 'Inc.',
        'status': 'active',
        'badges': ['2 relevant contracts', 'bridge to Pioneer Services'],
        'detailSnapshot': {
          'kind': 'client_company',
          'summary':
              'Cliente Summit com contrato ativo de TI e acordo expirado ainda relevante.',
          'rootCompanies': ['Summit Holdings'],
          'activeContracts': 2,
          'activeEmployees': 2,
          'indirectConnections': 1,
          'cta': {
            'label': 'Abrir empresa cliente',
            'targetPublicId': 'client_summit_solutions',
          },
        },
      },
      {
        'publicId': 'client_pioneer_services',
        'nodeType': 'client_company',
        'lane': 'client_company',
        'displayName': 'Pioneer Services',
        'subtitle': 'LLC',
        'status': 'active',
        'badges': ['shared delivery context', '2 visible employees'],
        'detailSnapshot': {
          'kind': 'client_company',
          'summary':
              'No central entre Summit e Pioneer, com contexto compartilhado de entrega.',
          'rootCompanies': ['Summit Holdings', 'Pioneer Group'],
          'activeContracts': 2,
          'activeEmployees': 2,
          'indirectConnections': 1,
          'cta': {
            'label': 'Abrir empresa cliente',
            'targetPublicId': 'client_pioneer_services',
          },
        },
      },
      {
        'publicId': 'client_pioneer_retail',
        'nodeType': 'client_company',
        'lane': 'client_company',
        'displayName': 'Pioneer Retail',
        'subtitle': 'Inc.',
        'status': 'active',
        'badges': ['1 historical contract'],
        'detailSnapshot': {
          'kind': 'client_company',
          'summary':
              'Cliente Pioneer com contrato expirado ainda material para leitura de historico.',
          'rootCompanies': ['Pioneer Group'],
          'activeContracts': 1,
          'activeEmployees': 1,
          'cta': {
            'label': 'Abrir empresa cliente',
            'targetPublicId': 'client_pioneer_retail',
          },
        },
      },
      {
        'publicId': 'client_pioneer_tech',
        'nodeType': 'client_company',
        'lane': 'client_company',
        'displayName': 'Pioneer Tech',
        'subtitle': 'LLC',
        'status': 'active',
        'badges': ['supply fallback context'],
        'detailSnapshot': {
          'kind': 'client_company',
          'summary':
              'Cliente tecnico que permanece visivel por conta do supply agreement expirado.',
          'rootCompanies': ['Pioneer Group'],
          'activeContracts': 1,
          'activeEmployees': 1,
          'cta': {
            'label': 'Abrir empresa cliente',
            'targetPublicId': 'client_pioneer_tech',
          },
        },
      },
      {
        'publicId': 'contract_retail_ops',
        'nodeType': 'contract',
        'lane': 'contract',
        'displayName': 'Retail Ops Agreement',
        'subtitle': 'Active',
        'status': 'active',
        'badges': ['1 active employee'],
        'detailSnapshot': {
          'kind': 'contract',
          'summary':
              'Acordo operacional da frente Summit Retail com leitura focada em execucao.',
          'contractStatus': 'active',
          'clientCompanies': ['Summit Retail LLC'],
          'activeEmployees': 1,
          'cta': {
            'label': 'Abrir contrato',
            'targetPublicId': 'contract_retail_ops',
          },
        },
      },
      {
        'publicId': 'contract_it_services',
        'nodeType': 'contract',
        'lane': 'contract',
        'displayName': 'IT Services Contract',
        'subtitle': 'Active',
        'status': 'active',
        'badges': ['2 client companies', '1 active employee'],
        'detailSnapshot': {
          'kind': 'contract',
          'summary':
              'Contrato ativo de TI que cruza Summit Solutions e Pioneer Services.',
          'contractStatus': 'active',
          'clientCompanies': ['Summit Solutions Inc.', 'Pioneer Services LLC'],
          'activeEmployees': 1,
          'cta': {
            'label': 'Abrir contrato',
            'targetPublicId': 'contract_it_services',
          },
        },
      },
      {
        'publicId': 'contract_consulting',
        'nodeType': 'contract',
        'lane': 'contract',
        'displayName': 'Consulting Agreement',
        'subtitle': 'Expired',
        'status': 'expired',
        'badges': ['historical employee context'],
        'detailSnapshot': {
          'kind': 'contract',
          'summary':
              'Contrato expirado que ainda precisa aparecer por manter contexto historico da Sarah.',
          'contractStatus': 'expired',
          'clientCompanies': ['Summit Solutions Inc.'],
          'activeEmployees': 0,
          'historicalEmployees': 1,
          'cta': {
            'label': 'Abrir contrato',
            'targetPublicId': 'contract_consulting',
          },
        },
      },
      {
        'publicId': 'contract_maintenance',
        'nodeType': 'contract',
        'lane': 'contract',
        'displayName': 'Maintenance Contract',
        'subtitle': 'Active',
        'status': 'active',
        'badges': ['2 active employees', 'selected employee anchor'],
        'detailSnapshot': {
          'kind': 'contract',
          'summary':
              'Contrato principal do recorte Pioneer Services, com Sarah como ancora do detalhe lateral.',
          'contractStatus': 'active',
          'clientCompanies': ['Pioneer Services LLC'],
          'activeEmployees': 2,
          'historicalEmployees': 1,
          'cta': {
            'label': 'Abrir contrato',
            'targetPublicId': 'contract_maintenance',
          },
        },
      },
      {
        'publicId': 'contract_supply',
        'nodeType': 'contract',
        'lane': 'contract',
        'displayName': 'Supply Agreement',
        'subtitle': 'Expired',
        'status': 'expired',
        'badges': ['historical retail context'],
        'detailSnapshot': {
          'kind': 'contract',
          'summary':
              'Acordo expirado que explica a permanencia de Pioneer Retail e Pioneer Tech no recorte.',
          'contractStatus': 'expired',
          'clientCompanies': ['Pioneer Retail Inc.', 'Pioneer Tech LLC'],
          'activeEmployees': 1,
          'cta': {
            'label': 'Abrir contrato',
            'targetPublicId': 'contract_supply',
          },
        },
      },
      {
        'publicId': 'employee_jessica_lee',
        'nodeType': 'employee',
        'lane': 'employee',
        'displayName': 'Jessica Lee',
        'subtitle': 'Project Manager',
        'status': 'active',
        'badges': ['Retail Ops Agreement'],
        'detailSnapshot': {
          'kind': 'employee',
          'summary':
              'Gestora operacional da frente Summit Retail dentro do acordo de retail ops.',
          'activeContracts': 1,
          'cta': {
            'label': 'Abrir pessoa',
            'targetPublicId': 'employee_jessica_lee',
          },
          'employeeId': 'EMP-09214',
          'email': 'jessica.lee@summitretail.com',
          'phone': '+1 (555) 830-2211',
          'department': 'Operations',
          'manager': 'Karen Miles',
          'clientCompany': 'Summit Retail LLC',
          'contract': 'Retail Ops Agreement',
          'statusLabel': 'Active',
          'startDate': 'Mar 04, 2021',
          'location': 'Seattle, WA',
        },
      },
      {
        'publicId': 'employee_michael_chen',
        'nodeType': 'employee',
        'lane': 'employee',
        'displayName': 'Michael Chen',
        'subtitle': 'IT Specialist',
        'status': 'active',
        'badges': ['IT Services Contract'],
        'detailSnapshot': {
          'kind': 'employee',
          'summary':
              'Especialista de TI alocado no contrato compartilhado entre Summit Solutions e Pioneer Services.',
          'activeContracts': 1,
          'cta': {
            'label': 'Abrir pessoa',
            'targetPublicId': 'employee_michael_chen',
          },
          'employeeId': 'EMP-09772',
          'email': 'michael.chen@summitsolutions.com',
          'phone': '+1 (555) 712-0092',
          'department': 'Infrastructure',
          'manager': 'Rachel Kim',
          'clientCompany': 'Summit Solutions Inc.',
          'contract': 'IT Services Contract',
          'statusLabel': 'Active',
          'startDate': 'Jul 18, 2022',
          'location': 'Austin, TX',
        },
      },
      {
        'publicId': 'employee_sarah_johnson',
        'nodeType': 'employee',
        'lane': 'employee',
        'displayName': 'Sarah Johnson',
        'subtitle': 'Senior Analyst',
        'status': 'active',
        'badges': ['Maintenance Contract', 'historical consulting context'],
        'detailSnapshot': {
          'kind': 'employee',
          'summary':
              'Analista senior com vinculo ativo em maintenance e passagem historica por consulting.',
          'activeContracts': 1,
          'historicalContracts': 1,
          'cta': {
            'label': 'View Full Profile',
            'targetPublicId': 'employee_sarah_johnson',
          },
          'employeeId': 'EMP-10432',
          'email': 'sarah.johnson@pioneerservices.com',
          'phone': '+1 (555) 234-5678',
          'department': 'Analytics',
          'manager': 'David Williams',
          'clientCompany': 'Pioneer Services LLC',
          'contract': 'Maintenance Contract',
          'statusLabel': 'Active',
          'startDate': 'Jan 15, 2022',
          'location': 'Chicago, IL',
        },
      },
      {
        'publicId': 'employee_david_williams',
        'nodeType': 'employee',
        'lane': 'employee',
        'displayName': 'David Williams',
        'subtitle': 'Account Manager',
        'status': 'active',
        'badges': ['Maintenance Contract'],
        'detailSnapshot': {
          'kind': 'employee',
          'summary':
              'Responsavel pela conta Pioneer Services dentro do contrato de maintenance.',
          'activeContracts': 1,
          'cta': {
            'label': 'Abrir pessoa',
            'targetPublicId': 'employee_david_williams',
          },
          'employeeId': 'EMP-10501',
          'email': 'david.williams@pioneerservices.com',
          'phone': '+1 (555) 778-1994',
          'department': 'Accounts',
          'manager': 'Laura Bennett',
          'clientCompany': 'Pioneer Services LLC',
          'contract': 'Maintenance Contract',
          'statusLabel': 'Active',
          'startDate': 'Nov 02, 2020',
          'location': 'Chicago, IL',
        },
      },
      {
        'publicId': 'employee_emily_davis',
        'nodeType': 'employee',
        'lane': 'employee',
        'displayName': 'Emily Davis',
        'subtitle': 'Operations Lead',
        'status': 'active',
        'badges': ['Supply Agreement'],
        'detailSnapshot': {
          'kind': 'employee',
          'summary':
              'Lider operacional preservada no recorte por conta do supply agreement expirado.',
          'activeContracts': 1,
          'cta': {
            'label': 'Abrir pessoa',
            'targetPublicId': 'employee_emily_davis',
          },
          'employeeId': 'EMP-10618',
          'email': 'emily.davis@pioneertech.com',
          'phone': '+1 (555) 448-9011',
          'department': 'Operations',
          'manager': 'David Williams',
          'clientCompany': 'Pioneer Tech LLC',
          'contract': 'Supply Agreement',
          'statusLabel': 'Active',
          'startDate': 'May 10, 2023',
          'location': 'Denver, CO',
        },
      },
    ],
    'edges': [
      {
        'publicId': 'edge_root_historical',
        'fromPublicId': 'root_summit_holdings',
        'toPublicId': 'root_pioneer_group',
        'relationshipKind': 'portfolio_history',
        'relationshipState': 'historical',
        'periodStart': '2023-01-01',
        'periodEnd': '2024-12-31',
        'metadata': {'label': 'historical portfolio overlap'},
      },
      {
        'publicId': 'edge_root_summit_retail',
        'fromPublicId': 'root_summit_holdings',
        'toPublicId': 'client_summit_retail',
        'relationshipKind': 'client_membership',
        'relationshipState': 'active',
        'periodStart': '2024-01-01',
        'periodEnd': null,
        'metadata': {},
      },
      {
        'publicId': 'edge_root_summit_solutions',
        'fromPublicId': 'root_summit_holdings',
        'toPublicId': 'client_summit_solutions',
        'relationshipKind': 'client_membership',
        'relationshipState': 'active',
        'periodStart': '2024-01-01',
        'periodEnd': null,
        'metadata': {},
      },
      {
        'publicId': 'edge_root_pioneer_services_from_summit',
        'fromPublicId': 'root_summit_holdings',
        'toPublicId': 'client_pioneer_services',
        'relationshipKind': 'shared_delivery_membership',
        'relationshipState': 'active',
        'periodStart': '2024-06-01',
        'periodEnd': null,
        'metadata': {'label': 'shared delivery context'},
      },
      {
        'publicId': 'edge_root_pioneer_services_from_pioneer',
        'fromPublicId': 'root_pioneer_group',
        'toPublicId': 'client_pioneer_services',
        'relationshipKind': 'client_membership',
        'relationshipState': 'active',
        'periodStart': '2024-01-01',
        'periodEnd': null,
        'metadata': {},
      },
      {
        'publicId': 'edge_root_pioneer_retail',
        'fromPublicId': 'root_pioneer_group',
        'toPublicId': 'client_pioneer_retail',
        'relationshipKind': 'client_membership',
        'relationshipState': 'active',
        'periodStart': '2024-01-01',
        'periodEnd': null,
        'metadata': {},
      },
      {
        'publicId': 'edge_root_pioneer_tech',
        'fromPublicId': 'root_pioneer_group',
        'toPublicId': 'client_pioneer_tech',
        'relationshipKind': 'client_membership',
        'relationshipState': 'active',
        'periodStart': '2024-01-01',
        'periodEnd': null,
        'metadata': {},
      },
      {
        'publicId': 'edge_client_bridge',
        'fromPublicId': 'client_summit_solutions',
        'toPublicId': 'client_pioneer_services',
        'relationshipKind': 'indirect_association',
        'relationshipState': 'indirect',
        'periodStart': '2025-01-01',
        'periodEnd': null,
        'metadata': {'label': 'shared delivery context'},
      },
      {
        'publicId': 'edge_retail_contract',
        'fromPublicId': 'client_summit_retail',
        'toPublicId': 'contract_retail_ops',
        'relationshipKind': 'contract_allocation',
        'relationshipState': 'active',
        'periodStart': '2024-02-01',
        'periodEnd': null,
        'metadata': {},
      },
      {
        'publicId': 'edge_it_contract_summit',
        'fromPublicId': 'client_summit_solutions',
        'toPublicId': 'contract_it_services',
        'relationshipKind': 'contract_allocation',
        'relationshipState': 'active',
        'periodStart': '2024-03-01',
        'periodEnd': null,
        'metadata': {},
      },
      {
        'publicId': 'edge_consulting_contract',
        'fromPublicId': 'client_summit_solutions',
        'toPublicId': 'contract_consulting',
        'relationshipKind': 'contract_allocation',
        'relationshipState': 'historical',
        'periodStart': '2023-01-01',
        'periodEnd': '2024-06-30',
        'metadata': {'label': 'expired consulting scope'},
      },
      {
        'publicId': 'edge_it_contract_pioneer',
        'fromPublicId': 'client_pioneer_services',
        'toPublicId': 'contract_it_services',
        'relationshipKind': 'contract_allocation',
        'relationshipState': 'active',
        'periodStart': '2024-03-01',
        'periodEnd': null,
        'metadata': {},
      },
      {
        'publicId': 'edge_maintenance_contract',
        'fromPublicId': 'client_pioneer_services',
        'toPublicId': 'contract_maintenance',
        'relationshipKind': 'contract_allocation',
        'relationshipState': 'active',
        'periodStart': '2024-04-15',
        'periodEnd': null,
        'metadata': {},
      },
      {
        'publicId': 'edge_supply_contract_retail',
        'fromPublicId': 'client_pioneer_retail',
        'toPublicId': 'contract_supply',
        'relationshipKind': 'contract_allocation',
        'relationshipState': 'historical',
        'periodStart': '2023-03-01',
        'periodEnd': '2024-11-30',
        'metadata': {'label': 'expired supply scope'},
      },
      {
        'publicId': 'edge_supply_contract_tech',
        'fromPublicId': 'client_pioneer_tech',
        'toPublicId': 'contract_supply',
        'relationshipKind': 'contract_allocation',
        'relationshipState': 'active',
        'periodStart': '2024-09-01',
        'periodEnd': null,
        'metadata': {'label': 'support continuation'},
      },
      {
        'publicId': 'edge_contract_bridge_one',
        'fromPublicId': 'contract_consulting',
        'toPublicId': 'contract_maintenance',
        'relationshipKind': 'indirect_association',
        'relationshipState': 'indirect',
        'periodStart': '2025-01-01',
        'periodEnd': null,
        'metadata': {'label': 'employee history overlap'},
      },
      {
        'publicId': 'edge_contract_bridge_two',
        'fromPublicId': 'contract_maintenance',
        'toPublicId': 'contract_supply',
        'relationshipKind': 'indirect_association',
        'relationshipState': 'indirect',
        'periodStart': '2025-01-01',
        'periodEnd': null,
        'metadata': {'label': 'shared retail account'},
      },
      {
        'publicId': 'edge_employee_jessica',
        'fromPublicId': 'contract_retail_ops',
        'toPublicId': 'employee_jessica_lee',
        'relationshipKind': 'employment_link',
        'relationshipState': 'active',
        'periodStart': '2024-02-10',
        'periodEnd': null,
        'metadata': {'label': 'current allocation'},
      },
      {
        'publicId': 'edge_employee_michael',
        'fromPublicId': 'contract_it_services',
        'toPublicId': 'employee_michael_chen',
        'relationshipKind': 'employment_link',
        'relationshipState': 'active',
        'periodStart': '2024-03-18',
        'periodEnd': null,
        'metadata': {'label': 'current allocation'},
      },
      {
        'publicId': 'edge_employee_sarah_historical',
        'fromPublicId': 'contract_consulting',
        'toPublicId': 'employee_sarah_johnson',
        'relationshipKind': 'employment_link',
        'relationshipState': 'historical',
        'periodStart': '2023-04-01',
        'periodEnd': '2024-02-29',
        'metadata': {'label': 'previous allocation'},
      },
      {
        'publicId': 'edge_employee_sarah_active',
        'fromPublicId': 'contract_maintenance',
        'toPublicId': 'employee_sarah_johnson',
        'relationshipKind': 'employment_link',
        'relationshipState': 'active',
        'periodStart': '2024-03-01',
        'periodEnd': null,
        'metadata': {'label': 'current allocation'},
      },
      {
        'publicId': 'edge_employee_david',
        'fromPublicId': 'contract_maintenance',
        'toPublicId': 'employee_david_williams',
        'relationshipKind': 'employment_link',
        'relationshipState': 'active',
        'periodStart': '2024-04-01',
        'periodEnd': null,
        'metadata': {'label': 'account owner'},
      },
      {
        'publicId': 'edge_employee_emily',
        'fromPublicId': 'contract_supply',
        'toPublicId': 'employee_emily_davis',
        'relationshipKind': 'employment_link',
        'relationshipState': 'active',
        'periodStart': '2024-09-10',
        'periodEnd': null,
        'metadata': {'label': 'operations lead'},
      },
    ],
    'filters': {
      'search': '',
      'applied': {
        'periodPreset': '1y',
        'rootCompanyPublicIds': [],
        'clientCompanyPublicIds': [],
        'contractStatuses': ['active', 'expired'],
        'employeeStatuses': ['active'],
        'includeHistorical': true,
        'includeIndirect': true,
      },
      'available': {
        'periodPresets': ['6m', '1y', '2y', 'all'],
        'rootCompanies': [
          {'publicId': 'root_summit_holdings', 'label': 'Summit Holdings'},
          {'publicId': 'root_pioneer_group', 'label': 'Pioneer Group'},
        ],
        'clientCompanies': [
          {'publicId': 'client_summit_retail', 'label': 'Summit Retail LLC'},
          {
            'publicId': 'client_summit_solutions',
            'label': 'Summit Solutions Inc.',
          },
          {
            'publicId': 'client_pioneer_services',
            'label': 'Pioneer Services LLC',
          },
          {'publicId': 'client_pioneer_retail', 'label': 'Pioneer Retail Inc.'},
          {'publicId': 'client_pioneer_tech', 'label': 'Pioneer Tech LLC'},
        ],
        'contractStatuses': ['active', 'expired'],
        'employeeStatuses': ['active'],
        'relationshipStates': ['active', 'historical', 'indirect'],
      },
    },
    'legend': {
      'relationshipStates': [
        {'value': 'active', 'label': 'Active Relationship'},
        {'value': 'historical', 'label': 'Historical Relationship'},
        {'value': 'indirect', 'label': 'Indirect Relationship'},
      ],
    },
    'focus': {
      'selectedNodePublicId': 'employee_sarah_johnson',
      'hoveredNodePublicId': null,
      'viewportAnchorPublicId': 'employee_sarah_johnson',
    },
  },
  'meta': {'traceId': 'req_01hnetworkcontractpreview0002'},
});
